os: linux
dist: bionic
sudo: required
language: c

env:
    global:
        - secure: "HSNS/028r6XSE7mYZQgDcBTyPwlN6XnZM+nmi7Cq5vlZskBT+ze3CAbOF3g53DR6ljrKNoX0sr41NYobzXtekMOA1tUEJTTvkQCMEkwucc3c3n2lEDTEY0VeVIzf3uMe2rDH0hg3u5fGiOdkqUDvEuDuVybB+PSbzsLjHUVUxsXtUCVKoyTITs4HLi0Rb/O05m2/mIJY+wW3K571i9ANzRzVhcP0FS4eamYNujNb1PPeYDMZax4racTKaCdfCUaADcF9dJOZRyQmHniBa5cYybIz1KD4tD/GlcW9gXfVeiBdVcDil4bT/1ojoh5KngGJkbm4/n78qgZikAFYpXzDLa0pxKJhIh+P07LdIrQx8ddH95D8u48vhSNpnmnygabgdKqB66lDfWBe1XrmwFTRaZPpOojBlvNQvgb+4xSUZxaRC7LSu4huNFRhvA++sxeaRNrsB5aPGAU4OtLylWYlmQmmLYyrjkha7L7TlMV3gwGbj6MTLLNbZuL/wP4b6Rqop5gzsjt5vTawQP2Eg8yOJSkCb1c7eovy0Su0zdc9kvuEPJS4B8ju2UvDs2ea7FZGBFTLqSiGXjFEaWHqPuJmXE9jUqE6sIHib/03czFUryyAtUQzxzgNBOX/fR2F5AUkJdalFwG6HL7h8lmmEHdrIZTY5d3UPwF0JfVNVColWgw="

addons:
    apt:
        packages:
            - build-essential
            - lsb-release
            - curl
            - ca-certificates
            - libslurm-dev
            - perl
            - cppcheck
    coverity_scan:
        project:
            name: "NVIDIA/pyxis"
            description: "Container plugin for Slurm Workload Manager"
        notification_email: fabecassis@nvidia.com
        build_command_prepend: "make clean"
        build_command: "make"
        branch_pattern: master

install:
    - sudo rm -f /etc/apt/sources.list.d/pgdg.list # Currently a bogus repo.
    - sudo apt-key adv --fetch-keys http://apt.llvm.org/llvm-snapshot.gpg.key
    - echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main" | sudo tee /etc/apt/sources.list.d/clang.list
    - sudo apt-get update
    - sudo apt-get install -y --no-install-recommends clang-9 clang-tools-9

jobs:
    include:
        - stage: build
          script:
              - make clean
              - CC=gcc make && make clean
              - CC=clang-9 make && make clean
              - cppcheck --std=posix --inconclusive --enable=all *.c *.h
              - scan-build-9 make && make clean
